//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCalendar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int idEvento { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> puntuacio { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> asistenciaMaxima { get; set; }
        public string localizacion { get; set; }
        public string descripcion { get; set; }
        public int TipoEvento_idTipoEvento { get; set; }
        public int Usuario_idUsuario { get; set; }
        public int Usuario_Entidad_idEntidad { get; set; }
    
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
