//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCalendar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Listar_Eventos
    {
        public string Nombre { get; set; }
        public string Categoria { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int idEntidad_User { get; set; }
        public int idEv { get; set; }
    }
}
