//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afegeix.
        /// </summary>
        public static string Add_Cat {
            get {
                return ResourceManager.GetString("Add_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string Add_Esp {
            get {
                return ResourceManager.GetString("Add_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Ing {
            get {
                return ResourceManager.GetString("Add_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Àlbum.
        /// </summary>
        public static string Alb_Cat {
            get {
                return ResourceManager.GetString("Alb_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Álbum.
        /// </summary>
        public static string Alb_Esp {
            get {
                return ResourceManager.GetString("Alb_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Alb_Ing {
            get {
                return ResourceManager.GetString("Alb_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista.
        /// </summary>
        public static string Art_Cat {
            get {
                return ResourceManager.GetString("Art_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista.
        /// </summary>
        public static string Art_Esp {
            get {
                return ResourceManager.GetString("Art_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Art_Ing {
            get {
                return ResourceManager.GetString("Art_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cercar.
        /// </summary>
        public static string Bus_Cat {
            get {
                return ResourceManager.GetString("Bus_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Bus_Esp {
            get {
                return ResourceManager.GetString("Bus_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Bus_Ing {
            get {
                return ResourceManager.GetString("Bus_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancelar_Cat {
            get {
                return ResourceManager.GetString("Cancelar_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar_Esp {
            get {
                return ResourceManager.GetString("Cancelar_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancelar_Ing {
            get {
                return ResourceManager.GetString("Cancelar_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netejar.
        /// </summary>
        public static string Clean_Cat {
            get {
                return ResourceManager.GetString("Clean_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string Clean_Esp {
            get {
                return ResourceManager.GetString("Clean_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Clean_Ing {
            get {
                return ResourceManager.GetString("Clean_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compositor.
        /// </summary>
        public static string Comp_Cat {
            get {
                return ResourceManager.GetString("Comp_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compositor.
        /// </summary>
        public static string Comp_Esp {
            get {
                return ResourceManager.GetString("Comp_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string Comp_Ing {
            get {
                return ResourceManager.GetString("Comp_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esborrar.
        /// </summary>
        public static string Del_Cat {
            get {
                return ResourceManager.GetString("Del_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Del_Esp {
            get {
                return ResourceManager.GetString("Del_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Del_Ing {
            get {
                return ResourceManager.GetString("Del_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genere.
        /// </summary>
        public static string Gen_Cat {
            get {
                return ResourceManager.GetString("Gen_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero.
        /// </summary>
        public static string Gen_Esp {
            get {
                return ResourceManager.GetString("Gen_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Gen_Ing {
            get {
                return ResourceManager.GetString("Gen_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Idio_Cat {
            get {
                return ResourceManager.GetString("Idio_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Idio_Esp {
            get {
                return ResourceManager.GetString("Idio_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Idio_Ing {
            get {
                return ResourceManager.GetString("Idio_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccioneu alguna cosa per cercar.
        /// </summary>
        public static string MenErrBus_Cat {
            get {
                return ResourceManager.GetString("MenErrBus_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona algo para buscar.
        /// </summary>
        public static string MenErrBus_Esp {
            get {
                return ResourceManager.GetString("MenErrBus_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select something to search.
        /// </summary>
        public static string MenErrBus_Ing {
            get {
                return ResourceManager.GetString("MenErrBus_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipus de mitjà.
        /// </summary>
        public static string MeTy_Cat {
            get {
                return ResourceManager.GetString("MeTy_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de medio.
        /// </summary>
        public static string MeTy_Esp {
            get {
                return ResourceManager.GetString("MeTy_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        public static string MeTy_Ing {
            get {
                return ResourceManager.GetString("MeTy_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mil·lisegons.
        /// </summary>
        public static string Mili_Cat {
            get {
                return ResourceManager.GetString("Mili_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milisegundos.
        /// </summary>
        public static string Mili_Esp {
            get {
                return ResourceManager.GetString("Mili_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string Mili_Ing {
            get {
                return ResourceManager.GetString("Mili_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom_Cat {
            get {
                return ResourceManager.GetString("Nom_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nom_Esp {
            get {
                return ResourceManager.GetString("Nom_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Nom_Ing {
            get {
                return ResourceManager.GetString("Nom_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cançó.
        /// </summary>
        public static string Tra_Cat {
            get {
                return ResourceManager.GetString("Tra_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canción.
        /// </summary>
        public static string Tra_Esp {
            get {
                return ResourceManager.GetString("Tra_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Tra_Ing {
            get {
                return ResourceManager.GetString("Tra_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preu Unitat.
        /// </summary>
        public static string UnPr_Cat {
            get {
                return ResourceManager.GetString("UnPr_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Unidad.
        /// </summary>
        public static string UnPr_Esp {
            get {
                return ResourceManager.GetString("UnPr_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnPr_Ing {
            get {
                return ResourceManager.GetString("UnPr_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualitzar.
        /// </summary>
        public static string Upd_Cat {
            get {
                return ResourceManager.GetString("Upd_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string Upd_Esp {
            get {
                return ResourceManager.GetString("Upd_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Upd_Ing {
            get {
                return ResourceManager.GetString("Upd_Ing", resourceCulture);
            }
        }
    }
}
